### ISSUE TITLE
error=homebrew tap formula: failed to publish artifacts: brew tap: no archives found matching criteria

### ISSUE THREAD

**Issue by yevgenypats** [goreleaser/goreleaser#1103]
**Describe the bug**

Getting the following message:

`error=homebrew tap formula: failed to publish artifacts: brew tap: no archives found matching criteria`

**To Reproduce**

The exact .goreleaser.yml can be found at

https://github.com/fuzzitdev/fuzzit/blob/master/.goreleaser.yml

**Expected behavior**

Expect it to publish the homebrew tap successfully and generate the formulat

**Environment (please complete the following information):**

- OS: mac
- OS version:
Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
- GoReleaser Version 
built at: 2019-08-06T11:52:35Z
built by: goreleaser

**Comment by caarlos0** [comment]
oh, its because your format is binary 🤔 

https://github.com/fuzzitdev/fuzzit/blob/master/.goreleaser.yml#L23

We don't support that :(

We could make the message clearer though.

BTW, you can add another archive just for homebrew, and on the brew section link it using the `ids` field.

https://goreleaser.com/homebrew/

Almost all pipes have some sort of id filtering, so maybe you'll have to fix them as well... 

hope it helps :)

**Comment by yevgenypats** [comment]
Hi! Thanks for prompt reply.

How do I add another archive?

**Comment by caarlos0** [comment]
`archives` is a list, just add another item :) 

https://goreleaser.com/archive/

**Comment by caarlos0** [comment]
not stale
