### ISSUE TITLE
getTag return incorrect tag, if we have more than 1 tag for 1 commit

### ISSUE THREAD

**Issue by andriisoldatenko** [goreleaser/goreleaser#1163]
**Describe the bug**
**To Reproduce**

1. Create new repo
```
mkdir test_goreleaser && git init
touch test.txt
git commit -m 'test'
```
than create few tags:
```
$ git tag 0.10.1-rc.3
$ git tag 0.10.1-rc.4
$ git tag 0.10.1-rc.5
$ git log
commit 278932bfb8d28c6346354e887b29d01eb4cb25d1 (HEAD -> master, tag: 0.10.1-rc.5, tag: 0.10.1-rc.4, tag: 0.10.1-rc.3)
Author: Andrii Soldatenko <andrii.soldatenko@gmail.com>
Date:   Tue Oct 1 16:27:42 2019 +0300

    init commit
```

if you run goreleaser it will run under the hood (`git describe --tags --abbrev=0`):
release tag `0.10.1-rc.3`

**Expected behavior**
goreleaser will release latest tag `0.10.1-rc.5`

**Environment (please complete the following information):**

- OS: all
- GoReleaser Version: master

More details you can find in this SO question: https://stackoverflow.com/questions/14273531/how-to-sort-git-tags-by-version-string-order-of-form-rc-x-y-z-w

**Comment by caarlos0** [comment]
fixed on #1164

**Comment by caarlos0** [comment]
had to revert #1164, will need to find another fix for this.

**Comment by aeneasr** [comment]
Could this be re-opened as this issue still persists?

**Comment by aeneasr** [comment]
Would it be possible to just rely on the CI information when it's available, e.g. `CIRCLE_TAG`? Sometimes we need to bump versions which don't necessarily have any changes because we keep versions of multiple projects in step. Because of this bug, we always have to create a dummy commit in order to be able to build the binaries using goreleaser, which is quite annoying and git history polluting :/

**Comment by caarlos0** [comment]
I commented my thoughts on the PR, but generally I think it should be OK yes! :)
