### ISSUE TITLE
Disable ldflags

### ISSUE THREAD

**Issue by diegobernardes** [goreleaser/goreleaser#1255]
**Is your feature request related to a problem? Please describe.**
I don't want to set any ldflags during my build.

**Describe the solution you'd like**
If no ldflags are set or in the case of a empty array, don't inject default values.

**Comment by caarlos0** [comment]
> If no ldflags are set or in the case of a empty array, don't inject default values.

this would be a breaking change... 

maybe you can set `-X 'main.SomethingThatDontExist=lalala'`, so it would actually have no effect?

**Comment by diegobernardes** [comment]
I'll do what you suggested. 
In the next major release this could be a optional parameter, what do you think?

**Comment by caarlos0** [comment]
yeah, maybe... but this could take a while, since we're not even v1 yet...

unfortunately, there's no clean way to change this without breaking things, so I rather not do this.

once v1 is out (hopefully next year), v2 will have all breaking changes we can possibly need, but the idea is to make v0.latest and v1 compatible 

thanks for the suggestion anyway, this was something I already had in mind for v2, will close it but will revisit it when the time comes.

thanks!
