### ISSUE TITLE
goreleaser check: run on every ci run?

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1289]
a couple of ideas I had to make it more noticeable to users when they're using deprecated configs:

1. warn at the end of `goreleaser release`
1. instruct to have another step that runs on every commit doing `goreleaser check`, maybe make exit code != 0 when deprecated settings are being used

any thoughts?

**Comment by joemiller** [comment]
I like #2 because I could see incorporating it into a project's CI (eg: `make lint` or `make test`) if I wanted to block and alert someone to make changes.

**Comment by matthiasng** [comment]
I agree with @joemiller.
For local testing, the output at the end of `goreleaser release` is fine, but inside a pipeline, a warning gets easily lost.

@caarlos0 
How about `goreleaser release --no-deprecated` instead of an additional command ? I think this will simplify the implementation a lot. The disadvantage is that you cannot add it to you quality checks pipeline steps.
