### ISSUE TITLE
Quotation aware string splitting

### ISSUE THREAD

**Issue by nmiculinic** [goreleaser/goreleaser#1375]
**Describe the bug**

In the current master pre/post hooks command is split on the whitespaces: 

https://github.com/goreleaser/goreleaser/blob/70c9e291ce035908de0890af08ebce386b670610/internal/pipe/build/build.go#L101

Thus when you have something like:
```
bash -c "do something more complex" 
```

or 
```
bash -c "echo {{.Version}} > dist/VERSION"
```

things fail miserably since argv isn't properly formatted. 

My goal use case is having the version written somewhere down the line (or have artifacts post hook also works for me

- GoReleaser Version [goreleaser --version]
```
version: 0.127.0
commit: 33d39188fa74ff03bb134b092386c9525da6b53a
built at: 2020-02-19T18:15:31Z
built by: goreleaser
```

**Comment by nmiculinic** [comment]
https://github.com/mattn/go-shellwords  this could be a solution perhaps?

**Comment by caarlos0** [comment]
well, this would otherwise probably be a breaking change, but this next release already have a breaking change on this particular part... so... maybe...

cc/ @radeksimko wdyt?

**Comment by radeksimko** [comment]
oh, interesting - I _think_ I may have bumped into this bug myself while testing #1414 but I never realized this was the root cause! 😄 - I just changed/avoided quoting or spacing or something and the problem went away, so I didn't pay further attention to it.

Out of curiosity what was the original motivation behind splitting the string in the first place? Could we not just pass the whole string to `exec.Command` as a single argument?

**Comment by caarlos0** [comment]
check https://github.com/goreleaser/goreleaser/pull/1437 :)
