### ISSUE TITLE
Dynamic data in ldflags

### ISSUE THREAD

**Issue by sagikazarmark** [goreleaser/goreleaser#141]
A quite common usage of ldflags is to add the actual commit hash and the build date to the binary, so it can be used in showing version information for example.

Is there a way in the current version which would help me achieve this?

Modifying the file in CI is an option, but I would rather avoid such hacks.

Thanks in advance.

**Comment by sagikazarmark** [comment]
Maybe supporting an [GORELEASER_]LDFLAGS environment variable would solve the problem.

**Comment by jorinvo** [comment]
hi @sagikazarmark does [this](https://github.com/goreleaser/goreleaser#a-note-about-mainversion) help? 
Otherwise you can only specify further ldflags via the configuration file. Would be more difficult to set a dynamic value that vaue.

**Comment by sagikazarmark** [comment]
No, it doesn't really, as I want to set the commit hash and a build date. [This](https://github.com/binhq/githubin/blob/master/.travis.yml#L28-L39) is what I am doing at the moment, but I am not happy about it.

**Comment by jorinvo** [comment]
@sagikazarmark I can see why you would like to improve on that 😉 

An environment variable or cli flag would probably be a good idea. 
However, this is kind of duplicating  the option from the configuration file. 
What do you think @caarlos0?

*Aside:*
Personally I prefer tools being configured completely via cli flags. They are self-documenting and explicit. Global values for environment variables can be tricky to deal with. 
I also prefer cli flags over configuration files since they can be inlined and can also be generated dynamically (as required in this issue). 
When configuration gets too complicated it's still possible to create a wrapper script as "configuration file".

I'm not suggesting removing the configuration file for GoReleaser though. Just wanted leave this note as we might have similar issues in the future. 
Since we already use environment variables for other things, (e.g. `GITHUB_TOKEN`), this is definitely also an option here.

Just pointing this out since from a user point of view it can be confusing to have three different ways to specify configuration and for each option you have to find the right way.

**Comment by sagikazarmark** [comment]
Personally I also think that flags are better, the reason I suggested an environment var is exactly the same as why you did: it's already in use.

From an inheritance point of view a flag probably would be better, as it would be clear that a flag provided execution time overrides what you have in the config. The same with an env var is not that clear.

I would probably take a look at cobra and viper as they already have a concept for cli config management.

**Comment by caarlos0** [comment]
Maybe allow the template in `ldflags` fields, and actually have the commit hash, date, etc available there?

**Comment by sagikazarmark** [comment]
That would solve my problems for now, wonder if anyone has any other use cases.

BTW when I say commit hash I mean the short version, not sure if adding both makes sense.
