### ISSUE TITLE
check deprecated travis config

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1433]
our travis config is giving us some warnings

![image](https://user-images.githubusercontent.com/245435/79047414-bd7ff780-7bec-11ea-9b31-a464b3cf78e0.png)

**Comment by joshuabezaleel** [comment]
Hi @caarlos0 , I am interested in this but I want to confirm a thing first. Does this mean that `goreleaser` has already use the travis' dpl v2? Since I open the docs and they said that it's still in a beta release phase. Thank you! :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/7043511/79172361-b6403000-7e1e-11ea-8270-e3f70292a048.png)

**Comment by caarlos0** [comment]
hmm the message lead me to believe they were deprecated on dpl v1 as well, and that they will not work on dpl v2, if that's not correct we can hold this issue for now 🤔

**Comment by wesleimp** [comment]
@caarlos0 this issue could be closed since the travis config has been removed on [this commit](https://github.com/goreleaser/goreleaser/commit/de9e989185ceb31c09d3edb53dd7be16098ee875)

**Comment by caarlos0** [comment]
true that, thanks!
