### ISSUE TITLE
goreleaser show Unable to get goreleaser version. today

### ISSUE THREAD

**Issue by codeskyblue** [goreleaser/goreleaser#157]
I have been use goreleaser for a long time. One day, goreleaser suddenly can't work.

Here is details of log in travis <https://travis-ci.org/openatx/wdaproxy/jobs/219609992>

**Comment by caarlos0** [comment]
Thanks for reporting this, I'll have a look

**Comment by caarlos0** [comment]
@codeskyblue  It seems OK here... maybe it was some instability in Github API... can you re-run the job and check if it works, please?

**Comment by codeskyblue** [comment]
it works when restart job

**Comment by whilei** [comment]
I'm running into the same issue. A restart worked once for me, but a second time it did not. Would of course rather not be restarting my jobs if I don't have to, either.

Might be worth adding a little debug output showing what, if anything, is returned from the Github API for this initial call yielding `Unable to get goreleaser version`.

```shell
0.38s$ curl -sL https://git.io/goreleaser | bash
Unable to get goreleaser version.
```

> https://travis-ci.org/whilei/janus/builds/252094592?utm_source=github_status&utm_medium=notification

**Comment by caarlos0** [comment]
do you have a `GITHUB_TOKEN` set for your build?

if not, it is accessing the API without a token, which has a very small rate limit. And you are sharing it with several travis users... so the failure is probably because of that.

We are working on solving this by generating the script on every release with the version hard coded, so we don't need to get the latest version for it to work. This may take some time to be implemented.

The quick win is to put the token on your travis-ci.

If it still not working, your token probably hit rate limit as well...

**Comment by caarlos0** [comment]
@whilei FWIW, I applied a quick fix that should fix the problem. You can see on issue #296

**Comment by whilei** [comment]
Thanks for touching base so quickly! 

The token is definitely set in the CI -- 
```shell
$ export GITHUB_TOKEN=[secure]
```
-- which makes me wonder if it's surely a rate limit problem, or perhaps something else? Not sure either way.

**Comment by caarlos0** [comment]
yeah, might be some other github limitation... either way it should be gone now.

**Comment by whilei** [comment]
👍  Right on, have been keeping tabs on your new `curl`. Looks good to me and is working. Simple for the win.

Please feel free to resolve.

**Comment by caarlos0** [comment]
fixed on https://github.com/goreleaser/get/commit/421486cbf3a885f0d2fb934e0b45a918b3e0149a
