### ISSUE TITLE
Doc: 404 errors on .gorelease.yml customization sub-categories pages

### ISSUE THREAD

**Issue by Jerome1337** [goreleaser/goreleaser#1633]
**Describe the bug**

Sometimes customization sub-categories links are broken.

**To Reproduce**

When you are on the [Quick Start Page](https://goreleaser.com/quick-start/) and you click on the `Customize` link after the `gorelease init` code block, the redirection works but every sub-categories (Archives, Blobs, ...) links are broken.

Only a `404 Not Found` title is shown

![image](https://user-images.githubusercontent.com/7968649/86229187-a4ee0080-bb8f-11ea-84f4-4eb25740ed2e.png)

The links seems to be wrong

For example:

```text
https://goreleaser.com/docker/
```

**Expected behavior**

Pages should work and show the expected documentation.

**Additional context**

Tested on Firefox `79.0b2`

**Comment by trungnn** [comment]
I think it doesn't work because the generated nav items are relative URLs and the link to Customization in the page you mentioned is `https://goreleaser.com/customization` which misses the final `/`. The browser will try to bring you to a non-existent page since it will take you to the wrong location (looking for Blobs inside root dir instead of customization).

I think this could be due to the way docs are being served. If you serve the docs locally with `mkdocs serve` then everything works as expected. I guess mkdocs knows automatically append the final `/` in the case it's missing. The fix could be to make sure all references in the docs end with a `/`, or look into how the docs are being served and make sure it's basically equivalant to `mkdocs serve`.

**Comment by caarlos0** [comment]
I can't reproduce this... for me the link works 🤔

**Comment by caarlos0** [comment]
> Tested on Firefox `79.0b2`

although I tested on firefox 78... lets wait for when firefox 79 is out :)

**Comment by Jerome1337** [comment]
@caarlos0 I just test and reproduce this on `Chrome Version 84.0.4147.89 (Official Build) (64 bits)`

**Comment by caarlos0** [comment]
Don't know what to say... tested here with Firefox, Chrome and Safari (all latest stables), and it works... 

https://img.carlosbecker.dev/goreleaser.mov

**Comment by caarlos0** [comment]
am I clicking on the right link?

**Comment by Jerome1337** [comment]
@caarlos0 Yes, the correct link

Video reproduction:

https://youtu.be/pf5pKs-Rd48

**Comment by caarlos0** [comment]
ohh, now I get it... I thought it was the customization page which wasn't working, not the sub pages... will take a look, thanks!

**Comment by caarlos0** [comment]
The fix is now live, thanks everyone, and sorry for me not understanding the problem 🙏
