### ISSUE TITLE
Using `brew` option to publish homebrew formula does not support signed commits.

### ISSUE THREAD

**Issue by timharris777** [goreleaser/goreleaser#1774]
I have goreleaser pushing the homebrew formula to a github repo that uses branch protection to require signed commits. Goreleaser is not signing the commit being pushed to the homebrew tap repo. 

- Looking in the code, under the hood it is using the github api instead of the git cli: https://github.com/goreleaser/goreleaser/blob/01fd3e8c7b3b16e77996b0434fc49f62a033f775/internal/client/github.go#L28
 
- Per the github api docs it does not look like the api supports signed commits: https://docs.github.com/en/rest/reference/repos#create-or-update-file-contents

Any chance this can be updated to use the git cli so that it will sign commits?

@venkatkotta , including you since you are trying to get around this as well

**Comment by radeksimko** [comment]
I think that using a native Git of some sort - either literally shelling to `git` or something like https://github.com/go-git/go-git - would be useful to also improve the security by enabling use of deployment keys, which basically require git over SSH. Right now the only way of authenticating is via PAT and PATs sadly still need to be associated with users.

With that in mind I would be personally inclined to such change, even though it may take some effort.

However I'd like for GoReleaser to still

 - retain relative freedom from external dependencies (which is why I'd personally favour go-git) and still ensure decent out-of-the-box experience
 - keep supporting token-based auth, so that integrations with GitHub Actions for example still work out of the box
 - keep git-over-HTTPS as default, at least initially, to prevent breaking changes for people who run GoReleaser in restricted environments, where tcp/22 isn't allowed

**Comment by caarlos0** [comment]
This would also require cloning the repo, which today it isn't.

**Comment by radeksimko** [comment]
@caarlos0 True, that increases the complexity a bit, I guess.

**Comment by caarlos0** [comment]
I would say this is very unlikely to happen, as it would make the entire thing more complex for very little marginal benefit, specially if assuming most people won't setup the CI git to sign commits anyway, which I seems to be the majority (I'm guessing based on what I have seen out there).

**Comment by radeksimko** [comment]
That's a fair assessment. I assume the best way forward would be for GitHub to bring that functionality (signing and deployment keys) into the API/SDK.

**Comment by caarlos0** [comment]
Yeah, will close for now. Please feel free to reopen if things change. Thanks!
