### ISSUE TITLE
proposal: remove root env section

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1831]
GoReleaser is not a CI, its a thing that is meant to be run as part of a CI pipeline. Global envs should be handled by that pipeline, not by GoReleaser itself, IMHO.

I propose we remove the global env (deprecate it first etc), and that will solve part of the problem we have in #1443 and #1795

WDYT?

**Comment by radeksimko** [comment]
I agree that most envs should be declared outside of GoReleaser.

That said there are two areas where they seem to be genuinely useful:

(1) reducing repetition of some parts of config, e.g. `flags` or `ldflags`

(2) reproducible builds, or _closer_ to reproducible. I _think_ that's likely what drives most people towards GoReleaser in the first place.

IMO people see GoReleaser as an elegant replacement for complex shell scripts. One of the benefits is that unlike shell scripts, GoReleaser binaries behave pretty much the same on all supported platforms and produce the same result, given the same config _and_ the same environment.

There will always be variables which need to be declared outside of the configuration for various reasons (secrets), but I think that `GO*` env variables shared between builds is a valid use case as these variables can drastically affect the build, so it's beneficial to keep them inside the config.

--- 

With that in mind I agree with removing current `env` in its current form, but I'd consider the following:

1. Introduce some kind of local `variables` which can be referenced in other parts of the config. I'm unsure what interpolation should these support (if any), but it may resolve the first use case. Then these variables could be also defined via flags (e.g. `goreleaser build -var=key1=val1 -var=key2=val2`) and then allowing interpolation would also address https://github.com/goreleaser/goreleaser/issues/1795 as one could set the variable value in the config to something like `{{ if env.VAR == "" ? "default" : env.VAR }}`.
2. Introduce `all_builds` to allow more scoped inheritance via `all_builds -> env` for `GO*` variables. Maybe someone will later ask for common variables for post hooks and this hierarchy would be able to support it - we could introduce `all_builds -> post_hooks_env` or something.

**Comment by radeksimko** [comment]
Actually maybe we don't need variables at all for the first use case - that could be resolved with an extra field under `all_builds`.

**Comment by 0xjac** [comment]
@radeksimko regarding 1. for the use case I have, local variables are perfectly fine. The issue is to provide a default, whether it's done locally or globally. That being said maybe having local values is indeed cleaner.

Having the option in the template, as you suggest, is fine for my use case (ie. `{{if .Env.SNAPSHOT_NAME}}{{.}}{{else}}dev{{end}}`) But it might not be for others... I find it also a lot missing but if this is the preferred way to go then it is a simple change: change the template option: [`missingkey=error`](https://github.com/goreleaser/goreleaser/blob/a92774f602331c53cd6b2c3c3ec8ec9058a26a7f/internal/tmpl/tmpl.go#L161) to `default` or `zero`. But this might have some serious consequences for some users. With a custom filename defined as: `/bin/{{ .Taf }}` where `.Taf` is a misspell of `.Tag`, then the output will be `/bin/` instead o triggering an error.

Overall, I feel like the environment variables in `goreleaser` are confusing because they overwrite external values. Most programs have a default value or behavior, and changing an environment variable when calling it can change the behavior. A simple example: `GOOS` and `go build`. On my system, `GOOS` is not defined, when I call `go build` it will take the default value `linux` on my system. If I want to build for another system, I can pass a different value when calling from the outside: `GOOS=darwin go build`.

With `goreleaser`, this is impossible. Let's assume we build some country-specific program and need to specify when building with`goreleaser`.

1. We define a variable `GO_COUNTRY_CODE=US` in the  `goreleaser` config.
2. When calling it it will build for the US and everything is fine.
3. However if we configure a build matrix in our CI to build one binary per country and define externally a different value for `GO_COUNTRY_CODE` (like `BR` or `UK`) then goreleaser will ignore those values and silently build US versions instead of the expected Brazil and UK versions.
4. If we remove the default `GO_COUNTRY_CODE=US`, then building our program without explicitly defining `GO_COUNTRY_CODE=US` will fail.

Having the values in the `env` section (global or not) act as fallback is much more intuitive option which solves the above and behaves more as developers expect env vars to behave.

**Comment by caarlos0** [comment]
ok, so, probably keeping the root env.

closing
