### ISSUE TITLE
Allowing the user to specify what docker binary to use

### ISSUE THREAD

**Issue by xocasdashdash** [goreleaser/goreleaser#1902]
**Is your feature request related to a problem? Please describe.**
I want to avoid using the docker daemon to build images
**Describe the solution you'd like**
Well, podman is flag compatible with docker so I'd like to be able to specify the binary that's used for building docker images. 

**Describe alternatives you've considered**
You could get away with using an alias "alias docker=podman" but I think specifying the docker path is a better solution

**Additional context**
I think this is key in order to avoid having a dependency on a docker daemon or access to one (by having your user be root)

**Comment by baez90** [comment]
I think one could get rid of the whole Docker stuff if one would integrate [buildah](https://github.com/containers/buildah) which could be completely integrated in the binary so no other binary would be needed at all? It even supports the manifests stuff already.

I think I could provide a PR for this if wanted.

**Comment by hoshsadiq** [comment]
I don't think it's as easy as specifying docker binary. I'm currently using podman 3.1.0, and using the docker compatible api (allowing me to use the `docker-ce-cli` binary) it's not working due to the `--load` flag that's hardcoded. Running the same command without `--load` (same with `--output=type=docker`). Same result if I use podman rootful and rootless. The output is below.

I think if buildah can be integration, my vote would go for `buildah` if possible.

```
$ docker buildx build . --load -t casdoor-testing --platform=linux/amd64
[+] Building 0.5s (6/7)
 => [internal] load build definition from Dockerfile                                                                                                                                       0.0s
 => => transferring dockerfile: 31B                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                            0.0s
 => [internal] load metadata for gcr.io/distroless/static:latest                                                                                                                           0.4s
 => [internal] load build context                                                                                                                                                          0.0s
 => => transferring context: 31B                                                                                                                                                           0.0s
 => [1/2] FROM gcr.io/distroless/static@sha256:60a7d0c45932b6152b2f7ba561db2f91f58ab14aa90b895c58f72062c768fd77                                                                            0.0s
 => => resolve gcr.io/distroless/static@sha256:60a7d0c45932b6152b2f7ba561db2f91f58ab14aa90b895c58f72062c768fd77                                                                            0.0s
 => CACHED [2/2] COPY casdoor /                                                                                                                                                            0.0s
 => exporting to oci image format                                                                                                                                                          0.0s
 => => exporting layers                                                                                                                                                                    0.0s
 => => exporting manifest sha256:20d59000fc2d1cb4dd528e50a2cd079650a63c4be0c2b4914d9509a03d5ce5d6                                                                                          0.0s
 => => exporting config sha256:47119d97a789e2f2eedefb67245d373c9a2c71f7bfd7dd4c7f630db295286451                                                                                            0.0s
 => => sending tarball                                                                                                                                                                     0.0s
error: failed to receive status: rpc error: code = Unavailable desc = transport is closing
```

Note: I got the above command from the debug output and just removed all the targets and labels. I've not tested it yet with other platforms either.

**Comment by caarlos0** [comment]
@hoshsadiq that's only when using buildx, which you can disable...

**Comment by hoshsadiq** [comment]
Sorry, only just saw this. Will cross-platform docker builds still work?

**Comment by caarlos0** [comment]
@hoshsadiq nothing on goreleaser code that prevents it, if podman work that should be enough yeah

agree that probably buildah integration would be a nice thing to have

**Comment by baez90** [comment]
It would be possible to integrate buildah in the goreleaser binary without breaking x-plat compatibility but buildah only works on Linux therefore it can also only be included in the Linux binary and needs to be shimed on all other platforms e.g. with a 'I won't do anything here' handler so no disadvantage but also no advantage for Windows users.

As @caarlos0 seems at least not to dislike the idea I'll see what I can do to create a PR but I can't promise anything about when I will be able to get to it.

**Comment by caarlos0** [comment]
yeah, was looking into that as well... 

windows is already a low priority citizen for goreleaser binaries, as its tar impl removes executable's permissions (for example)... and I'm sure there are more bugs, because the test suite fails in many places (#1947)

macOs on the other hand is used a lot... so not really sure about that...

**Comment by baez90** [comment]
To be honest I've no good solution for MacOS because Podman/Buildah are both not really suppported on MacOS at all (besides Podman-Machine, which is not really an option in this context).

One good thing about it would be - and I know this is kinda ironic - that integrating Buildah would allow to build images within Docker without a Docker socket and therefore unprivileged and in any kind of environment including Docker-in-Docker and rootless containers also on MacOS and Windows within a 'normal' Linux container.

I'm not sure if this is actually desirable - I would love it to be able to build images without a running daemon/access to a daemon because this makes it so much easier in CI environments.

**Comment by hoshsadiq** [comment]
Perhaps use build tags to keep current functionality for non-Linux environments and in Linux it uses buildah.

**Comment by baez90** [comment]
I was not thinking about how to get goreleaser actually still compiled - that's what I meant with a shim that will be included in all non-linux builds - but it's rather the question how do you proceed with buildah configs when goreleaser is invoked on Windows? Just skip it at all? Exit with an error? Try to fallback to Docker?

**Comment by baez90** [comment]
Having an extra `buildah` section and failing on unsupported OSs would be exactly what I had in mind but I wasn't sure how you prefer to handle this :sweat_smile: this way it would also be possible to support special Buildah flags without confusing any user about the background details.

**Comment by caarlos0** [comment]
podman support was just released in [goreleaser pro](https://github.com/goreleaser/goreleaser-pro/releases/tag/v0.173.0-pro).
