### ISSUE TITLE
auto-create release tags

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#198]
It would be great if you parsed a VERSION file or allowed it to be supplied to the goreleaser.yml and it would auto create the `git tag` then we could add a `release` command to our Makefiles that would just run goreleaser.

Similar to the way that https://github.com/progrium/gh-release works.

**Comment by caarlos0** [comment]
you can still automate it with make release:

```Makefile
release:
  git tag $version
  git push origin $version
  goreleaser
```

and then run it as:

```console
make release version=v1.2.3 
```

or, from a file:

```console
make release version=$(cat VERSION)
```
(or just make the cat inside the Makefile).

Anyway, it's not intended for goreleaser to create and push tags because that would add a lot of edge cases we would have to deal with, and, as I just shown, it is easy enough to automate without it :)

That being said, I'll close the issue. Thanks for trying goreleaser :)

**Comment by blacktop** [comment]
thanks for the great tool
