### ISSUE TITLE
Provide a make install

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#205]
With the new folder layout it's not possible to do a simple "go install" on the top level anymore, so it would be nice if the Makefile had a `go install` variant.

**Comment by jorinvo** [comment]
Personally, I try to use a `cmd` sub-directory only for projects that consist of more than one binary and for projects where the main artefact is a _package_ instead of a binary.
The way I understand GoReleaser the main artefact is the `goreleaser` binary. 
We can still provide the same functionality as a _package_ by moving the `goreleaser.go` file to `goreleaser/goreleaser.go`.
Is there any reason for moving the `main.go` file to `cmd/goreleaser` that I'm missing right now?

**Comment by caarlos0** [comment]
Wouldn't a `go get github.com/goreleaser/goreleaser/cmd/...` do?

**Comment by caarlos0** [comment]
@jorinvo not really, I was just trying to better organize the code...  AFAIK there isn't a pattern for that, I personally like to have the cmd package because I restrain myself to do cli stuff there... maybe it is dumb to do that, idk.

**Comment by bep** [comment]
>Wouldn't a go get github.com/goreleaser/goreleaser/cmd/.../go install ./cmd/... 

Maybe. 

But it would also give you the _Usability Fail Award of the Year 2017 Award_ :-)

**Comment by caarlos0** [comment]
yeah, I added the task anyway :D

**Comment by bep** [comment]
But I suspect most projects of this kind have a main func on the top level, making it "go gettable".

**Comment by jorinvo** [comment]
@caarlos0 we could keep the cli logic in a sub-directory and still re-add a top level `main.go` simply referencing it. Would that help keeping things organised?

**Comment by caarlos0** [comment]
closed by #206
