### ISSUE TITLE
GoReleaser Pro, open-source, and supply chain integrity

### ISSUE THREAD

**Issue by zwass** [goreleaser/goreleaser#2391]
Hi @caarlos0,

We've been pleased to integrate goreleaser into our release process for https://github.com/fleetdm/fleet/. In particular, making it easy to build all the necessary artifacts and upload in GitHub Actions has helped with my goal to improve transparency and address software supply chain integrity issues (discussed nicely in https://security.googleblog.com/2021/06/introducing-slsa-end-to-end-framework.html).

We are merging a couple of our repos, and purchased an enterprise license for GoReleaser Pro to support the project and utilize the monorepo functionality. I only just discovered that the goreleaser pro features are not open-source/source-available and require utilizing a separate binary. This conflicts with our goals to increase transparency and integrity in the full lifecycle of our software by adding an un-auditable dependency (GoReleaser Pro) into the build process.

Would you consider making the code source-available? I know this is a big ask, and it's something that we have contemplated quite a bit for our business. We've settled on making everything source-available using a [license](https://github.com/fleetdm/fleet/blob/main/LICENSE) that is inspired by [GitLab's License](https://docs.gitlab.com/ee/development/licensing.html).

Otherwise we may need to find ways to work around using GoReleaser Pro features in order to move forward with transparency in our build tooling.

Thank you for the consideration.

**Comment by caarlos0** [comment]
that's something I've been thinking about for a while now, both because of supply chain integrity and because it would make my life a lot easier.

the one thing that has been preventing me from doing that so far is the licensing thing.... but I guess that doing something like you do on fleet, maybe splitting the pro files and making it clear they have a different license.

I think @alexellis might have some good opinions to share as well.

**Comment by zwass** [comment]
FWIW @alexellis and I each have examples of multi-billion dollar companies handling it either way. I'm not asking you to do something that I don't stand behind -- my company makes the source available and we don't think piracy will be our ruin.

Of course @caarlos0 you'll have to make your own decision what you think will be best for you, your customers, and your OSS users.

I'll be disappointed, but understanding if you choose not to go down this path -- it just means we'll have to find (likely build?) alternatives for the enterprise features we might like to use.

**Comment by ryancurrah** [comment]
We have a build container image with everything required to build our Go binaries. We installed Pro on it and set the license as an environment variable. I'm not sure if that violates the license or not but it works currently.

**Comment by zwass** [comment]
@ryancurrah it's less the licensing we are concerned about, and more the transparency. We want to be able to provide as much transparency as possible to our users and customers about what has gone into the binaries we ship. If we build those binaries with an opaque artifact like GoReleaser Pro, that introduces quite a reduction in the transparency we can provide.

**Comment by ryancurrah** [comment]
I can def see it being an issue if go releaser was something you were shipping to customers, but ensuring that all the tools you use to build your software is completely open source is super pedantic and unnecessary. Since Go Releaser stays in your environment and not customers I don't see why a customer would care. Following your logic it would mean you would need GitHub Actions source code since maybe that's what you use as your CI tool or the source doe for any other tool that comes in contact with your binary. ⬇️

**Comment by caarlos0** [comment]
> We have a build container image with everything required to build our Go binaries. We installed Pro on it and set the license as an environment variable. I'm not sure if that violates the license or not but it works currently.

shouldn't be an issue, no :)

**Comment by caarlos0** [comment]
> Is your enterprise license bringing in 6 figures of revenue per year?

I wish 😂 






> FWIW @alexellis and I each have examples of multi-billion dollar companies handling it either way. I'm not asking you to do something that I don't stand behind -- my company makes the source available and we don't think piracy will be our ruin.

I totally understand, but goreleaser don't have a company or vcs behind it, its just me, working on my free time.

I do understand your point though - that's why I have been thinking about it a lot. At the same time, I'm curious if @ryancurrah latest comment makes sense for your case as well... because in my head it does 🤔

I thought for a while in a 3rd option: having a license that also gives access to the source, but I think that would still not solve the problem, someone along the chain will still not have access to it...

maybe making the source available is something that might happen once I have X revenue or Y customers or something like that, but as @alexellis pointed out, I'm pretty sure someone somewhere will pirate it.

so, after thinking a whole lot more, I still don't know what I'm going to do here.

**Comment by zwass** [comment]
@ryancurrah GoReleaser is the thing that _builds_ everything we want to ship to customers. This means any compromise in GoReleaser is a potential compromise of (y)our customers. 

If this seems theoretical, please catch up on the recent [SolarWinds attack](https://www.csoonline.com/article/3191947/supply-chain-attacks-show-why-you-should-be-wary-of-third-party-providers.html), which specifically targeted the build infrastructure.

Looking at this from the [SLSA](https://slsa.dev/levels) perspective, 

> [Level 2] prevents tampering to the extent that the build service is trusted.

Where we're at with the closed, non-source available GoReleaser Pro is that "the build service" includes not only GitHub Actions (Microsoft), but @caarlos0 himself. While I am relatively certain Carlos has good intentions, that doesn't make him invulnerable to compromise, particularly when compromising Carlos could lead to compromising the customers of everyone who relies on his build tooling (eg. he could potentially be a very high value target for a threat actor).

From my perspective this leads to us being better off using GoReleaser in some way other than via Pro. This is (so far) clearly a minority opinion.

**Comment by marcosnils** [comment]
> @ryancurrah GoReleaser is the thing that _builds_ everything we want to ship to customers

GoReleaser just execs the standard `go build` command to build your code, you can still `go build`

**Comment by caarlos0** [comment]
@zwass you could also set `gomod.proxy` to true, and make your binary verify itself against the go mod proxy (e.g. print the module sum et al)... does that help?

**Comment by zwass** [comment]
> you could also set gomod.proxy to true, and make your binary verify itself against the go mod proxy (e.g. print the module sum et al)... does that help?

Maybe I'm misunderstanding, but I'm not sure how the module proxy would help -- Maybe it allows someone to verify the dependencies that were used in the build, but it doesn't let us know that the source code for GoReleaser was not tampered with intentionally or by a malicious actor on your systems.

> GoReleaser just execs the standard go build command to build your code, you can still go build it first and then do a sha check to make sure GoReleaser is generating the same binary.

GoReleaser also does a bunch of other things that I find useful -- that's why I paid for an enterprise license. Sure, I can generate every artifact GoReleaser does separately, but then why use GoReleaser at all?

**Comment by marcosnils** [comment]
> GoReleaser also does a bunch of other things that I find useful -- that's why I paid for an enterprise license. Sure, I can generate every artifact GoReleaser does separately, but then why use GoReleaser at all?

I'm just saying you can re-build (using go cache) one of your outputs just to validate that GoReleaser is not changing your binaries somehow if you *need* a BSOM process in your organization. I don't see a strong argument to open source it due to fact that GoReleaser uses the go tool chain to build your program.

**Comment by caarlos0** [comment]
if you build proxying from go proxy, you can verify the binary built is the actual tag with `go version`:

```
❯ go version -m (which goreleaser )
/usr/local/bin/goreleaser: go1.16.6
	path	github.com/goreleaser/goreleaser
	mod	github.com/goreleaser/goreleaser	v0.174.2	h1:EltDZkVGq0mC2Aqgc7uGT7A0aaXdt4KPV6OxTmUG4pk=
	dep	cloud.google.com/go	v0.81.0	h1:at8Tk2zUz63cLPR0JPWm5vp77pEZmzxEQBEfRKn1VV8=
	dep	cloud.google.com/go/storage	v1.15.0	h1:Ljj+ZXVEhCr/1+4ZhvtteN1ND7UUsNTlduGclLh8GO0=
	dep	code.gitea.io/sdk/gitea	v0.14.1	h1:NaRluse+dAxVM5RmHC7Xktfas5a8WWmcnUBlJLhJycA=
	dep	github.com/AlekSi/pointer	v1.1.0	h1:SSDMPcXD9jSl8FPy9cRzoRaMJtm9g9ggGTxecRUbQoI=
...
```

vs build directly from source:

```
/usr/local/bin/goreleaser: go1.16.6
	path	github.com/goreleaser/goreleaser
	mod	github.com/goreleaser/goreleaser	(devel)
	dep	cloud.google.com/go	v0.81.0	h1:at8Tk2zUz63cLPR0JPWm5vp77pEZmzxEQBEfRKn1VV8=
	dep	cloud.google.com/go/storage	v1.15.0	h1:Ljj+ZXVEhCr/1+4ZhvtteN1ND7UUsNTlduGclLh8GO0=
	dep	code.gitea.io/sdk/gitea	v0.14.1	h1:NaRluse+dAxVM5RmHC7Xktfas5a8WWmcnUBlJLhJycA=
	dep	github.com/AlekSi/pointer	v1.1.0	h1:SSDMPcXD9jSl8FPy9cRzoRaMJtm9g9ggGTxecRUbQoI=
	dep	github.com/Azure/azure-pipeline-go	v0.2.3	h1:7U9HBg1JFK3jHl5qmo4CTZKFTVgMwdFHMVtCdfBE21U=
	dep	github.com/Azure/azure-sdk-for-go	v54.0.0+incompatible	h1:Bq3L9LF0DHCexlT0fccwxgrOMfjHx8LGz+d+L7gGQv4=
```


you can also verify that the hash is correct by doing something like this:

```sh
mkdir /tmp/test
cd /tmp/test
go mod init test
go get github.com/goreleaser/goreleaser@v0.174.2
grep 'h1:EltDZkVGq0mC2Aqgc7uGT7A0aaXdt4KPV6OxTmUG4pk=' go.sum
```

but, of course, instead of goreleaser, that would be your own binary.

that way, doesn't really matter where or how the binaries were built, you can verify it is the actual tag and also all its dependencies.

does that help?

**Comment by marcosnils** [comment]
IIUC @zwass concern is not how to check which goreleaser version was used to build the program, but how actually goreleaser is doing it.

**Comment by caarlos0** [comment]
> Even if they can validate the GoReleaser has in the proxy, the project author (or any other intruder) could potentially craft a release that introduces some backdoor or vulnerability.

the idea is not to validate goreleaser, but to the binary built by goreleaser...

**Comment by caarlos0** [comment]
FWIW I tried to clarify my points a bit here: https://carlosbecker.com/posts/supply-chain-goreleaser-go-mod-proxy/

**Comment by marcosnils** [comment]
> FWIW I tried to clarify my points a bit here: https://carlosbecker.com/posts/supply-chain-goreleaser-go-mod-proxy/

Now I see what you're saying Carlos. However this is still not a very strong way which guarantess that `GoReleaser` couldn't be changing your binary somehow. Since `go build` works locally offline, it could still tamper the $GOPATH/pkg/mod/cache` ziphashes and make `go version -m` print whatever hash it wants there. 

i.e: 

```
mkdir /tmp/lala && cd /tmp/lala && go mod inity lala
go get github.com/faith/color
echo 'package main
import "github.com/fatih/color"
func main() {
  color.Red("hola")
}
```
After this you can simply do: 

```
$ go mod vendor 
# Change the vendored code to do whatever you want
$ go build 
```
At this point, `go version -m <binary>` will still include the original has fetched from the go proxy. However, the code built in the resulting binary is different.  I'm aware that you can still use `go build -mod readonly` to force `go build` not use the vendored folder, but since `Goreleaser` does the `go build` call, the user is pretty much blind about that.

I still don't see how this could be achieved without a proper signing process or building the binaries separately with and without goreleaser and comparing hashes..

WDYT? 

PS the last example in your blog post doesn't seem to work for me. I'm getting this when trying to build the program

```
go build github.com/caarlos0/svu
/home/marcos/Projects/gopath/pkg/mod/github.com/caarlos0/svu@v1.7.0/internal/git/git.go:9:2: missing go.sum entry for module providing package github.com/gobwas/glob (imported by github.com/caarlos0/svu/internal/git); to add:
        go get github.com/caarlos0/svu/internal/git@v1.7.0
```

**Comment by marcosnils** [comment]
> FWIW I tried to clarify my points a bit here: https://carlosbecker.com/posts/supply-chain-goreleaser-go-mod-proxy/

I wrote a previous response that I deleted since I was misunderstanding how the `proxy` feature was used in Goreleased. Now that I looked at the docs a bit more, I still believe that some of previous thoughts still apply. 

Since Goreleaser handles the building part of the binary, it could be easily vendoring the dependency locally, changing whatever code and then performing a `go build -mod vendor`. The resulting output of the `go version -m <binary>` will still look the same since the build part happens locally and the `go` command doesn't require any soft of external proxy hash validation for this. 

Since Goreleaser handles all the build setup magic, I don't see to many ways besides signing and has comparison to effectively validate that goreleaser is building the correct binary.

**Comment by caarlos0** [comment]
> Since Goreleaser handles the building part of the binary, it could be easily vendoring the dependency locally, changing whatever code and then performing a `go build -mod vendor`. The resulting output of the `go version -m <binary>` will still look the same since the build part happens locally and the `go` command doesn't require any soft of external proxy hash validation for this. To check this out, you can simply grab any go program, vendor and modify any of it's dependencies and you'll see that after re-building, the embedded module hashes will still be the same ones without the vendor modifications.

hmm, you're right, will need to update my post.



> Any ideas why?.

no idea, tested again in the latest go docker image and it works fine 🤔

**Comment by caarlos0** [comment]
updated the post https://carlosbecker.com/posts/supply-chain-goreleaser-go-mod-proxy#edit

thanks for the comments @marcosnils , I missed the whole vendor thing 🤔

**Comment by caarlos0** [comment]
I also opened an issue to Go, because it seems to me that this should not happen 🤔

https://github.com/golang/go/issues/47935

**Comment by marcosnils** [comment]
> I also opened an issue to Go, because it seems to me that this should not happen

Awesome! thought about opening an issue as well.. but no no time here :)



> no idea, tested again in the latest go docker image and it works fine

I'm using 1.16 here (can't upgrade now). Still wondering why it fails :thinking:

**Comment by caarlos0** [comment]
> I'm using 1.16 here (can't upgrade now). Still wondering why it fails 🤔

it should work on go 1.16 as well... 🤔

**Comment by marcosnils** [comment]
> it should work on go 1.16 as well...

Found the reason, some old go cache :disappointed:

**Comment by zwass** [comment]
> IIUC @zwass concern is not how to check which goreleaser version was used to build the program, but how actually goreleaser is doing it.

> Even if they can validate the GoReleaser has in the proxy, the project author (or any other intruder) could potentially craft a release that introduces some backdoor or vulnerability.

This is a good summary of my concerns. Our intent is that users can minimize the number of trust links in the supply chain, and as of now GoReleaser is a potential weakness.
