### ISSUE TITLE
[Bug]: try to avoid second time push if builder engine supports flags like '--publish' or '--push'

### ISSUE THREAD

**Issue by erkanzileli** [goreleaser/goreleaser#2462]
We (@Dentrax  and @developer-guy ) are trying to add the Buildpack support and we realized that the Buildpack is able to publish images on the `build` command with `--publish` [flag](https://github.com/buildpacks/pack/blob/a7487c97057e931e2eb1187fad46e39a505b750d/internal/commands/build.go#L19) which means users can publish images on the Build step but the goreleaser also calls Publish method of imagers.

Also, we realized that the `buildx` usage of docker supports publish images with the `--push` [flag](https://docs.docker.com/engine/reference/commandline/buildx_build/#options). In that way, the goreleaser tries to publish images twice (both on Build and Publish methods of the imager interface).

In both situations, users can specify the `--publish` flag for the Buildpacks and the `--push` flag for `buildx` in the [build_flag_templates](https://goreleaser.com/customization/docker/#applying-docker-build-flags) of the `docker` section.

**Comment by lbernail** [comment]
Hello. I found the issue while looking for a solution to use the docker buildx driver without a docker daemon.

Context:
- we use remote builders (we configure buildx to use the kubernetes driver) so we have a docker client but no docker socket
- the current steps for docker builds (with or without buildx) is to build and load the image in the local daemon during the Build phase and the push during the Publish phase
- since we don't have a daemon buildx with `--load` fails

Ideally we'd want to use `--push` instead of `--load` and bypass the publish step

In addition, buildx supports creating a multiarch images directly, it would be nice to avoid using manifest and simply use buildx to build for all platforms and create and push a multiarch image (this might more complex).

More than happy to help prototype this

**Comment by caarlos0** [comment]
yeah, this is a problem indeed, mostly because I don't know what the right abstraction for this should look like. 

Docker manifests suffer from the same issue, and because of that we need to create the images first and then the manifest, but it could be a single docker manifest cmd that builds the images and manifests and push them.

For now, I think you can workaround this by setting `skip_push` to true and add the `push` flag in the docker configs.

The side effects are that the docker images won't be listed in the release notes and unless you template the flags it might end up pushing the images on snapshots as well...

My greatest concerns about changing this are backwards compatibility and making sure we won't push things when the user is not expecting us to. Maybe we could start prototyping that...

**Comment by lbernail** [comment]
@caarlos0 I've been thinking about this and I can see 2 paths (for buildx)
- integrate with buildx better: single buildx command with multiple goos and goarch building a multiarch image and direct push to registries
- add a `build-output` parameter to the "docker" builder which would default to `type=docker` but can be set to `type=docker,dest=<output-file-template>`. When default is used, the docker image will be loaded in the local daemon but when a dest is provided, the file will be written to disk on the client. Then we can import `github.com/google/go-containerregistry/pkg/crane` to push the docker image spec tarball to registries in the publish phase (and just push normally for the default config)

Option 1 is more aligned with the builx model but it will be hard to maintain backward compatibility
Option 2 will easily allow for backward compatibility, can work with and without buildx, and aligns well with the goreleaser model

What do you think? I can likely prototype option 2 in the next few days (option 1 will require more thoughts on design before we can do something)
 
(for the build-output param in option I reused the output syntax from https://docs.docker.com/engine/reference/commandline/buildx_build/#output which will allow us to support additional options such as oci images in the future, but we can of course use a different name and different options)

@erkanzileli sorry for hijacking your issue

**Comment by caarlos0** [comment]
The way goreleaser works is splitting this process in 2 phases:

- building things
- publishing things

IF the user purposefully puts `--push` or `--publish` on their configs, and later its pushed again, the second push should be a noop and therefore not a problem assuming a successful release.

The biggest concern here is, IMHO, if the image is built and push, but some other step later fails before the actual publish phase, the image will already be there...
This is also not that bad as it can be re-published later... but its a concern anyway.

That all being said, my take here would be:

- leave what's already there as-is
- start working on another impl using "more native" stuff (e.g. what ko does)

wdyt?

**Comment by caarlos0** [comment]
will leave as is for now
