### ISSUE TITLE
[Bug]: buildpack docker backend still requires Dockerfile

### ISSUE THREAD

**Issue by justinharringa** [goreleaser/goreleaser#2491]
### What happened?

Hey there folks! First, the support for buildpacks added in #2461 is really cool. Unfortunately, this appears to require that there is a `Dockerfile` in the repo (unless I'm missing some configuration).

After adding `pack` to my runner via:
```
      - name: Set up Buildpacks
        uses: buildpacks/github-actions/setup-pack@v4.1.0
```

And switching to buildpack, I got the following before it started to build: `failed to copy dockerfile: failed to copy Dockerfile to dist/goreleaserdocker3823241621/Dockerfile: lstat Dockerfile: no such file or directory`

I was able to successfully run by just adding a dummy `Dockerfile` to the repo: https://github.com/justinharringa/test-goreleaser/blob/main/Dockerfile

### How can we reproduce this?

Instead of using `Dockerfile`, switch `dockers` in `.goreleaser.yml` to:

```
dockers:
- image_templates: ["ghcr.io/github-org/github-repo:{{ .Version }}"]
  use: buildpacks
```

Sample repo: https://github.com/justinharringa/test-goreleaser/blob/main/.goreleaser.yml

### goreleaser version

```bash
v0.179.0/goreleaser_Linux_x86_64.tar.gz
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I may take a look at contributing a fix if I get a chance.

**Comment by caarlos0** [comment]
hmm, indeed

a workaround for now is either create an empty Dockerfile or set `dockerfile` to any other file, since its not being used, it should work.

cc/ @developer-guy we should think about a solution to this 🤔

maybe a `defaulter` interface inside the docker package, with one impl for docker and another for buildpacks? wdyt?

**Comment by justinharringa** [comment]
cool - thanks for the quick response @caarlos0!

**Comment by developer-guy** [comment]
we have to take care of this problem @Dentrax @erkanzileli.

**Comment by developer-guy** [comment]
@caarlos0 would you mind to assign this issue to me ?

**Comment by erkanzileli** [comment]
> maybe a `defaulter` interface inside the docker package, with one impl for docker and another for buildpacks? wdyt?

as I understand, you're saying that in the Buildpacks **defaulter** we should create an empty Dockerfile?
I thought if we do that and if the user doesn't ignore the Dockerfile from the .gitignore file this causes a dirty **git** state, I guess it will fail us because it isn't expected.

Maybe we can change [this code](https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/docker/docker.go#L154) like this

```golang
if docker.Use != useBuildPack {
  if err := gio.Copy(docker.Dockerfile, filepath.Join(tmp, "Dockerfile")); err != nil {
	  return fmt.Errorf("failed to copy dockerfile: %w", err)
  }
}
```

@caarlos0 wdyt ?

**Comment by caarlos0** [comment]
Sounds good as well 🙏
