### ISSUE TITLE
Integrate with GitHub auto-generated release notes

### ISSUE THREAD

**Issue by jawnsy** [goreleaser/goreleaser#2552]
GitHub recently launched a new feature for [automatically generating release notes for releases](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/). This is an issue to discuss what, if anything, GoReleaser might want to do in order to support this.

**Describe the solution you'd like**
I'd like to understand what impact the new GitHub auto-generated release notes might have on GoReleaser: does this warrant some sort of change to GoReleaser code, will this be a transparent change to the releases already published, or something else?

**Describe alternatives you've considered**
None, this is a pretty fresh announcement! :tomato:

**Comment by caarlos0** [comment]
Yeah I was just playing with it, should be easy enough to integrate.

Also see #2548

**Comment by caarlos0** [comment]
ps, usage with curl is something like:

```sh
curl -sf -XPOST --header "Authorization: Bearer "$GITHUB_TOKEN https://api.github.com/repos/goreleaser/goreleaser/releases/generate-notes -d '{"tag_name": "v0.180.3", "previous_tag_name": "v0.180.2"}' | jq -r '.body'
```

**Comment by caarlos0** [comment]
FWIW, raised a pr to go-github adding it as a feature: https://github.com/google/go-github/pull/2114

**Comment by kinoute** [comment]
Would it be possible at the same time to add an option in order to generate changelog entries as a list ? (eg. with the use of "-" or "*"). It looks better that way:

<img width="555" alt="Capture d’écran 2021-11-04 à 14 25 47" src="https://user-images.githubusercontent.com/623763/140321300-c2fd2173-1de1-4cd9-abb4-b10db393e287.png">

I think Github auto-generates changes as a list too. I make a PR if needed. It seems it can be changed here directly: https://github.com/goreleaser/goreleaser/blob/48d774970c3a47af150964ddd8cf37e8e6943ef6/internal/pipe/changelog/changelog.go#L60-L70

**Comment by caarlos0** [comment]
@kinoute can you please open another issue about it? Thankss
