### ISSUE TITLE
Upload to AWS S3

### ISSUE THREAD

**Issue by novusopt** [goreleaser/goreleaser#266]
Would be a nice feature to support upload to AWS s3 buckets.

**Comment by andygrunwald** [comment]
From my thoughts, the implementation can be quite similar to #429.
If this will be a success, we may can move some functionality to the goreleaserlib (e.g. making the http call). Anyhow. #429 could possibly used as a base, because S3 is just similar to Artifactory (if you see them just as an object storage)

**Comment by andygrunwald** [comment]
Comment to prevent that the stale bot closes this. I still think this is useful.
