### ISSUE TITLE
[Idea] Make Changelogs Smarter - Diff between non-pre-release tags only

### ISSUE THREAD

**Issue by ekristen** [goreleaser/goreleaser#2764]
**Is your feature request related to a problem? Please describe.**
No, this is an idea to enhance the changelog feature.

**Describe the solution you'd like**
As it stands the changelog feature presumably (based on testing) generates a diff between the current tag and the previous tag, regardless of the meaning of the tag in semver.

For example, if the previous tag was v2.0.0-rc2 and the current is v2.0.0 and there was a single commit between the two that is all that would show up in the changelog, even though there might have been 100 commits between v1.0.0 and v2.0.0-rc2.

I think that anytime `prerelease` is set to `auto` that it would be awesome to have the changelog feature look further back in the tags and attempting to identify the last non pre-release tag. If it doesn't find one, then fallback to it's normal operating method.

I think for the pre-release tags there are three options (maybe a config flag)

1. Each time a pre-release tag is created it works as normal, showing the changelog from last tag to current tag
2. Each time a pre-release tag is created it sees if there's another pre-release before it, and does a rollup, like everything from the previous rc, plus the current one
3. Or it only diffs against the last non-pre-release and shows that changelog each time it's cut, the pre-release always having the full changelog from last non pre-release tag.

**Implementation details**

I actually don't think this would be too terrible difficult to implement, it would ultimately come down to looking further back in history for tags and comparing semver information.

**Comment by kwyn** [comment]
Been trying to find a standalone changelog go tool that does this well and have been struggling. So the unfortunate thing is that this would be a change to https://github.com/goreleaser/chglog not goreleaser but they're within he same project if not GitHub repo. 

So that being said I think chglog the underlying tool would require updates not goreleaser itself except for propagating some of this configuration upwards to the goreleaser semantic versioning. 
Details being:
1. Update https://github.com/goreleaser/chglog to be able to filter pre-release commits. Would need to be injected conditionally somewhere around [here](https://github.com/goreleaser/chglog/blob/master/init.go#L32)
2. Have that filter act conditionally on a new config [here](https://github.com/goreleaser/chglog/blob/master/cmd/chglog/config.go#L9) best guess would be to have a "ignore pre-release" flag or something similar to https://github.com/caarlos0/svu#discarding-pre-release-and-build-metadata

Then one could have two different build parameterizations one for pre-release and one for GA. Though probably not the best solution but that would be the simpler one than having some deep running side effects through.

Given how lightweight chglog is and it's opinions state in the readme for chglog not sure if it's tenable since it'd be changing the *main* part of the very lightweight tool. But maybe the maintainer is up for it!

The above implementation doesn't handle your 2nd case but we could massage the implementation details around filtering and configuration. Unfortunately it's currently quite late when I'm writing this so I might come back and hash out the details for the 2nd case as well as some naming for what the configuration property and values might be called.

**Comment by caarlos0** [comment]
https://github.com/goreleaser/chglog is not used to generate goreleaser's changelogs...

workaround: you can set a `GORELEASER_PREVIOUS_TAG` env if you can get it easily via some command or something

**Comment by ekristen** [comment]
Oh that's an interesting idea. That would be easy enough. Still think first class support would be great! Thanks for the amazing tool

**Comment by caarlos0** [comment]
thanks @ekristen , at this time will not implement this in goreleaser itself.

users can always pipe the output of other changelog tools into goreleaser (via `--release-notes` flag), and just building release notes is already something with a rather big scope, so I'd rather keep it as simple as possible for now.

cheers!
