### ISSUE TITLE
Goreleaser pulling incorrect tag information

### ISSUE THREAD

**Issue by stack72** [goreleaser/goreleaser#2943]
### What happened?

In the past 3 days Goreleaser 1.5 has started killing incorrect tag information causing the builds to fail.

Goreleaser now seems to pull an SDK/<name> tag as the latest tag when previously it ignored these. This has started happening since the latest release of the GitHub Action

previously: https://github.com/pulumi/pulumi-azure-native/runs/5333434160?check_suite_focus=true#step:10:42

now: https://github.com/pulumi/pulumi-azure-native/runs/5358588814?check_suite_focus=true#step:10:43

### How can we reproduce this?

Create a tag of a repo vx.x.x and sdk/vx.x.x and Goreleaser gha is failing 

### goreleaser version

```bash
1.5.0 Linux amd
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This seems to be related to the v2.9.0 release of the GitHub action

**Comment by caarlos0** [comment]
cc/ @crazy-max 

I don't see why it started breaking now, though...

in any case, do we really need this? https://github.com/goreleaser/goreleaser-action/compare/v2.8.1...master#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR61 

seems to me that, if the user sets it, goreleaser will get it from the parent process, and if doesn't , this is getting in the way of how goreleaser resolves the tag...


that said, I'm fairly confident its not it, as you're actually setting the current tag, and the tag breaking is the previous one.

I can reproduce this by running `goreleaser release --rm-dist --snapshot` on the master branch.

---

All that being said, goreleaser itself didn't have a release since a couple of weeks ago, so its more likely something in your repo changed, or maybe the git version being used.

goreleaser gets the current branch and previous branch with:

```
# Current
git -c log.showSignature=false describe --always --dirty --tags

# Previous
git -c log.showSignature=false describe --tags --abbrev=0 --match=* tags/$CURRENT^
```

in my local test, both current and previous tags are prefixed with `sdk`.

**Comment by crazy-max** [comment]
Hum looks like there is an issue with `GORELEASER_CURRENT_TAG`. Will take a look.

**Comment by stack72** [comment]
@caarlos0 we are setting the GORELEASER_CURRENT_TAG but it's not being respected 

https://github.com/pulumi/pulumi-azure-native/runs/5358588814?check_suite_focus=true#step:10:31

**Comment by caarlos0** [comment]
oh, sorry, I misunderstood...

released @crazy-max's fix at v2.9.1, can you verify @stack72?

**Comment by stack72** [comment]
Will check now @caarlos0 :) thanks to you and @crazy-max

**Comment by stack72** [comment]
Circling back here - sorry for being late - this does indeed fix the issue! thank you

**Comment by caarlos0** [comment]
amazing! 

thanks for reporting!
