### ISSUE TITLE
Protect the Windows Build tar.gz with a Password to bypass Corporate Checks

### ISSUE THREAD

**Issue by abdennour** [goreleaser/goreleaser#3357]
### Is your feature request related to a problem? Please describe.

In some organization, any file of extension .exe cannot be downloaded.. And any compressed file includes "*.exe" cannot be downloaded as well.

### Describe the solution you'd like

The only way to download this kind of files is to compress it with a protected password.

### Describe alternatives you've considered

1. Manually download the file `tool-windows-amd64-v1.0.0.tar.gz`
2. zip it with protected password `zip -P mypass123 -r tool-windows-amd64-v1.0.0-protected-mypass123.zip tool-windows-amd64-v1.0.0.tar.gz`
`
3. Push the protected zip file to a private repo 
4. Users can download it without issues

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

as end-user, i would assume a goreleaser.yml to look like following after this feature:
```
builds:
  - main: main.go
    protection:
      password: mypass123
      goos:
       - windows

```

**Comment by caarlos0** [comment]
The config should probably be in the archives section instead of builds.

In any case, I honestly don't see this as something a lot of people will use to release software... if someone asks me to password protect goreleaser archives I would not do it... 


["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.

Cheers!
