### ISSUE TITLE
Allow multiple releases for one project

### ISSUE THREAD

**Issue by Arsen6331** [goreleaser/goreleaser#3428]
### Is your feature request related to a problem? Please describe.

I have a project (https://github.com/Arsen6331/lure) that's mirrored from my Gitea instance to Github. I'd like GoReleaser to create releases on both the Gitea repo and the Github mirror. When I try this currently, GoReleaser gives me an error saying that multiple releases cannot be used at the same time.

### Describe the solution you'd like

Allow multiple releases to be used simultaneously.

### Describe alternatives you've considered

There aren't any alternative solutions I can think of.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
This would be a really big endeavor as it would require quite a bit of refactory. 

FWIW: You can already get this by setting only either github or gitea token and maybe abusig templates a bit, so, it would be a lot of work and extra complexity for not much benefit, specially since not many projects need this.

["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.
