### ISSUE TITLE
goreleaser build should skip changelog

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#3510]
#3507

**Comment by fguisso** [comment]
I'm trying to start work on this issue, but make some testing, the first behavior using `goreleaser init` doesn't create the `github-native` tag inside the yml. Why this is a bug if the user needs to specify that? Maybe just improve the documentation and fix this?

If it's really a bug, can you describe more what are the expected behavior, please?

**Comment by caarlos0** [comment]
@fguisso just had to move a couple of lines around, already did it on #3520
