### ISSUE TITLE
Add support for depot.dev

### ISSUE THREAD

**Issue by flemzord** [goreleaser/goreleaser#3746]
### Is your feature request related to a problem? Please describe.

I would like to improve the build time of my Docker images

### Describe the solution you'd like

I wish I could tell GoReleaser to use depot.dev instead of buildx or podman

### Describe alternatives you've considered

No longer use GoReleaser to build my Docker images

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobwgillespie** [comment]
Hey! 👋 I'm one of the cofounders of Depot, I'd love to see an integration with GoReleaser!

For some background, Depot provides hosted BuildKit/buildx builders as a service. The [depot CLI](https://github.com/depot/cli) wraps buildx build with auth for the remote builder, so `depot build ...` accepts all the same CLI flags as `docker buildx build` would.

I think the direct way to integrate Depot and GoReleaser would be to offer a `use: depot` backend that calls `depot build --load ...` in place of the current `docker buildx build`. That would behave similarly to the `use: buildx` backend.

A more optimized integration would be to integrate with buildx's `--push` flag - you can skip downloading the built container to the local Docker image store by not including `--load` and instead calling `depot build --push`. That buildx flag both builds and pushes the image directly from the remote buildx builder, which saves both the network time and the time tarballing the image into Docker's format. This might be more involved though, since my understanding is that GoReleaser expects build and push to be two separate steps today.

Let me know your thoughts and what I can do to help.

**Comment by caarlos0** [comment]
if anyone wants to try to pr it, I can review.

as far as the build and push in a single go, its how we implemented Ko, maybe its worth having its own implementation like Ko does too...

**Comment by caarlos0** [comment]
Is anyone interested in working on this integration?

**Comment by caarlos0** [comment]
I'm not interested in working on this, so, if no one volunteers, I'll close the issue.

That said, I think a better integration would be to make the `depot` cli configure auth on the client, and then the user can use the `buildx` builder as usual.

**Comment by WitoDelnat** [comment]
Hey! We'd like to use goreleaser with Depot.dev and I noticed that there is a draft PR. I'm wondering if something is blocking the pull request from being merged? The integration would be much appreciated.

**Comment by caarlos0** [comment]
sorry, I'm closing this. I just don't have the energy to maintain this, and it doesn't seem to be asked for a lot, so I'm leaving it out for now.

["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.
