### ISSUE TITLE
`zip` support; having `format: zip` results in `do not know how to unpack source archive /nix/store/dvl2hd8i63dq4xw76l49l1is6i3yh0nk-blah_0.0.1_darwin_all.zip`

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#4224]

**Comment by lionello** [comment]
Hey @caarlos0 I think you'd want to add it to `inputs`, not `dependencies`, no? It's basically the same as `makeWrapper`.

**Comment by caarlos0** [comment]
@lionello Its how I saw other packages doing it in nixpkgs... is it wrong?

**Comment by lionello** [comment]
I think it's not necessary to add to `dependencies`, but it wouldn't hurt either.

**Comment by lionello** [comment]
@caarlos0 I don't think this is fixed, since the Nix files generated with v1.22.1 are still missing the `unzip` dependency.

See https://github.com/defang-io/defang/actions/runs/7283416033/job/19847250711#step:6:16 and the generated file https://github.com/defang-io/defang/blob/f9d759d961baf6c0baf53e28402fdc71f04ad8b3/pkgs/defang/default.nix

**Comment by caarlos0** [comment]
ah, different case, URLs mixing formats... will fix, thanks for reporting 🙏

**Comment by caarlos0** [comment]
see https://github.com/goreleaser/goreleaser/pull/4495
