### ISSUE TITLE
Support for splitting release without pushing Docker images

### ISSUE THREAD

**Issue by dejanzele** [goreleaser/goreleaser#4258]
### Is your feature request related to a problem? Please describe.

I have a robust CI on GitHub Actions where I first run my tests & lints, then a new workflow which does some validation and if it is successful it starts the release job which is using GoReleaser.

Because my CI is slow as all of the jobs take quite a bit to run, my idea for optimising it is to have a job which builds & dockerises my applications ahead of time while my test & lint workflow runs, and then if test & lints complete successfully, and also the validation passes, I continue the GoReleaser process which would push the Docker images and do other stuff (SBOM, checksums, announcing...)

### Describe the solution you'd like

I looked into GoReleaser Pro and nightlies feature (https://goreleaser.com/customization/nightlies/), but it looks like even if I use `--split`, it still will push the Docker images instead of doing that in the `goreleaser continue --merge` command.

Is there a native way for separating the release process in the way I described it, having a warmup job which builds & dockerizes my applications, and then in a different workflow I continue the release process which will then do docker push and all of the rest?

### Describe alternatives you've considered

I can accomplish the described behaviour if my warmup job (job which builds & dockerises the applications) runs `goreleaser release --snapshot --skip-sbom --skip-sign` and then in my release workflow I have a custom script which does `docker push` for all of the Docker images.

In this case, I don't even need GoReleaser Pro, but I would be happy to keep my upgrade to GoReleaser Pro as I use this tool for quite some time now, and it is one of my favourite tools, if I can solve my problem and do all of the steps with GoReleaser and remove the need for a custom Docker push script.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Hey! 

You're right, it does push the images on split. 
That's needed because the idea is to split the build into several runners, so, the runner that does the merge only creates the manifests from these images. We can't delay the push, because we don't know where the merge job will run, it might be even on a different OS. 

My recommendation would be to make the images be `owner/name:{{ .Commit }}`, and add a `docker_manifests` configuration with the actual final name you want (e.g. `owner/name:{{.Version}}`).

It'll still push the image, but it'll clearly be an intermediary image.

Hope that helps!

**Comment by caarlos0** [comment]
(I'll close the issue, but feel free to continue commenting here :) )
