### ISSUE TITLE
continue --merge fails with custom dist folder

### ISSUE THREAD

**Issue by fredcarle** [goreleaser/goreleaser#4551]
### What happened?

I've specified the `dist` folder in the `.goreleaser.yaml` file and on `continue --merge`, the process fails with the error `did not find any contexts to merge`. When removing that configuration, the process succeeds. 

### How can we reproduce this?

Use the same setup as https://github.com/goreleaser/goreleaser-pro-split-merge-example-real but specify the `dist` folder in the `.goreleaser.yaml` file and make sure the cache directories have the same base path.

### goreleaser version

```bash
goreleaser/goreleaser-action@v5
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [x] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I see, good catch, will fix!

Thanks

**Comment by caarlos0** [comment]
for continue to work on a folder different than the default, you'll need to use `goreleaser continue --dist ./folder`

This is required because on continue it doesn't parse the configuration file, instead, it loads the previous context. This allows to run `continue` with the dist folders without any source, with the bad side effect that `dist` will not be automatically carried on.

I'll document this better.
