### ISSUE TITLE
improve release changelog

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#56]
Ideas:

- get merged PR titles and link them instead of the commit
- lone commits (which were not merged within a PR) can be linked as it is today

**Comment by sagikazarmark** [comment]
I would like to add "turning off" changelog as an improvement here. For regular, small releases it's probably okay to have some log, but for larger term releases it might not fit that well. Also, some workflows might require the users themselves to update the change log file together with the change.

Maybe add a custom template option which can contain a custom text or a link to a changelog file?

I would probably keep the generated notice nevertheless, so that users know, developers know, etc.

**Comment by jorinvo** [comment]
I think a template might be too much.
If someone really needs to customise the release note they can do so manually on GitHub (or using another script).

**Comment by caarlos0** [comment]
I agree @jorinvo.

Let's close this, if it becomes an issue we can alway do it later :)
