### ISSUE TITLE
release notes generator based on PR history

### ISSUE THREAD

**Issue by buchanae** [goreleaser/goreleaser#612]
I wrote a release notes generator for our project. It generates notes based on GitHub Pull Request history. PRs are a much better source of documentation, comments, timeline, and otherwise human-readable content related to a change, in my opinion.

The code is here: https://github.com/ohsu-comp-bio/funnel/blob/master/util/github-release-notes/main.go

It's output looks like this: https://github.com/ohsu-comp-bio/funnel/releases/tag/0.6.0

Any interest in integrating this into goreleaser?

**Comment by caarlos0** [comment]
if you distribute it as a binary, you can already use it `goreleaser --release-notes <(./generator)`

the problem is that there are a lot of projects that don't use github for example. Folks also customize with sections and things like that... I think that if we add this, it will be logical to add a lot more, which I'm not sure I want to add/maintain/etc (code is a liability).

That being said, what do you think?
Maybe a section in docs about the usage of this - and I'm sure there are others - changelog generators?

**Comment by buchanae** [comment]
> if you distribute it as a binary, you can already use it goreleaser --release-notes <(./generator)

Ya, that's how we're using it currently, and I should probably give it a clean CLI and repo/release.

> the problem is that there are a lot of projects that don't use github for example.

And even lots of projects that don't use GitHub PRs like we do too.

> I think that if we add this, it will be logical to add a lot more, which I'm not sure I want to add/maintain/etc

I agree, probably a slippery slope.

Since it's not a clear "yes", let's close this. I'll comment here when the generator is cleaned up and put in its own repo.

**Comment by caarlos0** [comment]
> Since it's not a clear "yes", let's close this. I'll comment here when the generator is cleaned up and put in its own repo.

OK, nice =D

I think we can put a list of changelog generators on docs to aid this as well =)

**Comment by buchanae** [comment]
https://github.com/buchanae/github-release-notes

**Comment by caarlos0** [comment]
/remind me this issue in 8 hours

**Comment by caarlos0** [comment]
done
