### ISSUE TITLE
Add support for the AUR (Arch Linux)

### ISSUE THREAD

**Issue by cjbassi** [goreleaser/goreleaser#641]
I think it would be cool if goreleaser was able to create PKGBUILD's and also submit them to the AUR if possible. PKGBUILD's for binary blobs are actually fairly simple. [Here's](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=gotop-bin) the one I'm currently using for my project and I just update the version number each release.

Details:
* the package name should end in '-bin' by default since it's a binary package
* the case switch of $CARCH is only needed if 32bit is supported in addition to 64bit
* PKGBUILD's are submitted to a git repo hosted by the Arch community

**Comment by TylerBrock** [comment]
This would be awesome, are there any objections to supporting this or building it out?

**Comment by caarlos0** [comment]
no objections, no, just didn't had time to work into this... PRs are welcome :D

**Comment by daehyeok** [comment]
@caarlos0  Are you willing to add this feature to goreleaser and nfpm? then i will trying :)

**Comment by caarlos0** [comment]
we won't generate an actual package right? as fas as I know, the PKGBUILD is kind of a shell script... 

That being said, I vote to do that on goreleaser itself...

I don't know, though, how to publish an AUR package and how complex it is...

**Comment by cjbassi** [comment]
Yah a PKGBUILD is just a shell script.

The AUR is a git repository host, with the git repositories being the packages. In our case, the package would just include a PKGBUILD and a .SRCINFO file which is just a more easily parseable PKGBUILD. A .SRCINFO file is generated on Arch Linux with `makepkg --printsrcinfo > .SRCINFO` while in a folder with a PKGBUILD, although it shouldn't be difficult to replicate that command.

So the way you would publish an AUR package is to clone the repo from the AUR, update the PKGBUILD and .SRCINFO, commit, and then push it.

**Comment by NurdTurd** [comment]
👍

**Comment by AnatolyRugalev** [comment]
For ones who interested in implementation details, you can check out [this repo](https://github.com/AnatolyRugalev/kube-commander)

I [bash-scripted](https://github.com/AnatolyRugalev/kube-commander/tree/master/ci/aur/publish.sh) publishing process and it should be easy to port into Goreleaser itself.

There are some caveats though:
1. `PKGBUILD` and `.SRCINFO` are build from a dead simple templates. If this is the way to go, we should provide ability to replace this templates. Otherwise there will be no customization at all.
2. Developers need to add private SSH key to project to push to AUR (travis encrypted files, for example)
3. There is a `pkgrel` field in AUR which should be incremented if the same version of package (`pkgver`) is being updated

I think I can make a PR if you're OK with this implementation.

**Comment by caarlos0** [comment]
> I think I can make a PR if you're OK with this implementation.

sounds good to me!
