### ISSUE TITLE
Go plugin builder

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#662]
**Is your feature request related to a problem? Please describe.**

We would like to ship and use plugins within GoReleaser.

Go supports both Linux and macOS for now.

**Describe the solution you'd like**

The idea is to have a plugin builder so 3rd parties can use it to write plugins for goreleaser.

**Describe alternatives you've considered**

hashicorp's plugin system, which I believe is more complex than we need it to be.

**Additional context**

check #654 and #520

**Comment by caarlos0** [comment]
https://github.com/golang/go/issues/22462

seems like it is not that straightforward to do that... maybe hashicorp's lib is a better option indeed

**Comment by caarlos0** [comment]
ok, at this point I'm just lying to myself here... closing this for the time being.

**Comment by aegershman** [comment]
I realize this is closed, and what I'm about to add is half-baked, _but_:

It might be worth watching what happens in the [`buildpack` space](https://github.com/buildpack/pack) for ideas on patterns & abstractions to follow for what a clean plugin system might look like. Buildpacks are designed for building/running software using pluggable packages and bundles, with the end result being an OCI image with a built endstate. The thing to steal being this idea of pluggable builds. 

It's probably not possible to actually _use_ buildpacks in this context-- since the end result of a chain of buildpacks is a runnable OCI image rather than an arbitrary binary-- but just something to consider, I guess.

This feels like a pretty hard problem, honestly. Pardon my unsolicited opinion, though I don't think anyone would begrudge `goreleaser` maintainers for putting a **generalized, language-agnostic plugin interface for build systems** on the backburner lol

Just blabbing, sorry for commenting on a closed issue with this ¯\\_(ツ)_/¯

**Comment by caarlos0** [comment]
Will take a look... but for now I don't think we'll add this :(

**Comment by aegershman** [comment]
Hey I mean it's called "_go_-releaser" for a reason 😉

thanks for all you that you all do 👍

**Comment by caarlos0** [comment]
yeah haha

but I really wanted to that at some point... because most of the releasing thing is the same... just the build is different... 

anyway, would be hell-ish to maintain I think :D 



> thanks for all you that you all do 👍

thanks 🙏
