### ISSUE TITLE
Docker images missing extra files

### ISSUE THREAD

**Issue by kaihendry** [goreleaser/goreleaser#695]
**Describe the bug**

I need to add the [sql/ directory](https://github.com/unee-t/invite/tree/master/sql) with my binary. Same use case with html templates.

Following https://goreleaser.com/customization/#Docker

I added the files like so
https://github.com/unee-t/invite/blob/master/goreleaser.yml

Sidenote: sql/ or sql/* would have been nicer. They don't appear to work either.

**To Reproduce**

Apologies for these terrible steps, I don't know Docker too well:

1. `docker pull uneet/invite` # ensure you have the latest version
2. `docker run --name goreleaserbug uneet/invite` and ctrl+c 
3. `docker export goreleaserbug > /tmp/contents.tar`
4. `tar tf /tmp/contents.tar  | grep sql`

**Expected behavior**

The extra sql files to be included.

**Environment (please complete the following information):**

- OS: Archilinux
- OS version: Linux t480s 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
- GoReleaser Version 5629759

**Additional context**

https://twitter.com/caarlos0/status/1004893593058861059

Furthermore development iterations when I am trying different configs. I hit for example when I re-issue `goreleaser`:

    [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]

**Comment by caarlos0** [comment]
You need to add those files to your docker file as well.

Example commit: https://github.com/caarlos0/github_releases_exporter/commit/72c728e9073a1259ad0128f8cb48d2715fbf8d1d

I think you can add the entire directory by specifying just the directory name...

---

About the `[{Resource:ReleaseAsset Field:name Code:already_exists Message:}]` error, is by design, you need to create a new tag or delete the previous releases.

**Comment by kaihendry** [comment]
You're right! It's working with a similar project: https://github.com/unee-t/unit/blob/master/Dockerfile

Sidenote: Is it possible to get binary files name "unit" as a templated variable and inserted please?
