### ISSUE TITLE
seperate tool for creating brew formula like nfpm

### ISSUE THREAD

**Issue by tahsinrahman** [goreleaser/goreleaser#755]
**Is your feature request related to a problem? Please describe.**

We want to create homebrew formula, but do not want to use goreleaser for that purpose. We're using makefile. We are using nfpm for creating deb and rpm packages. It will be handy we could use a Homebrew specific cli to create brew formulas.

**Describe the solution you'd like**
Like what you did with nfpm, it'd be great if brew part of the goreleaser was also a separate tool.

**Describe alternatives you've considered**
We tried to separate brew part of goreleaser for our internal use https://github.com/appscodelabs/brew-tool
But it'll be hard to maintain. We also don't want to do what is already there! So it'd be great it there is a seperate tool for creating brew formula like nfpm. We are happy to contribute to split out Homebrew part into its own cli.

**Comment by caarlos0** [comment]
Hi @tahsinrahman 

Thanks for the suggestion, but I don't think its worth doing that... since you'll use on a single project, is probably easier to have the file in your repo and just replace things like version and sha256 sum using `evnsubst` or something like that.

NFPM is separated because it was born a separated tool, even though it's cli is very limited.

Cheers!
