### ISSUE TITLE
Support for library projects?

### ISSUE THREAD

**Issue by dmjones** [goreleaser/goreleaser#981]
I've used goreleaser in the past for projects with binaries and I like it. I'm now working on a Go library  (i.e. no `main` function) and I would still like to use goreleaser to produce nice release notes and source zips/tars.

Is there any interest in supporting this use case? Based on #415 and #418, it suggests not. What about a flag in the config that disables builds?

**Comment by caarlos0** [comment]
there isn't, but I was thinking about "externalizing" the changelog generator.. just haven't done it yet :P

**Comment by andersfylling** [comment]
Any news on this? Given how many libraries/modules is out there, this would be of interest?

@dmjones did you find an alternative?

**Comment by leogr** [comment]
Hey @caarlos0 
Any change to reconsider this feature? 

It would be great having that by enabling an option in the config to skip the building step.
IMHO, just "externalizing" would not be enough because the GitHub release still needs to be created with the changelog attached. For example, I would like to use that in my CI pipeline.

Thanks in advance!

PS @dmjones @andersfylling did you find an alternative?

**Comment by caarlos0** [comment]
I think there are probably other tools that already do this, no?

**Comment by leogr** [comment]
Maybe my fault, but I could not find anything as good as `goreleaser` :stuck_out_tongue:

Btw, if you wanted to support this, I would happy to help.
That being said, I will not insist anymore. :innocent:

**Comment by andersfylling** [comment]
I simply gave up on this @leogr

**Comment by caarlos0** [comment]
I think the only thing relevant for a library project would be the changelog generation and creating the release, right?

We could maybe add another binary that does only the changelog and release parts 🤔Or maybe a `--release-only` flag... or maybe on builds set a flag `library: true` and ignore it... 

The fact is: I don't know how a good api for that would look, neither the side effects

We can try to hack something together though... I'll open to it if we find a good way of doing it...

**Comment by andersfylling** [comment]
In the end I realised that was I wanted, was something that can:
1. changelog generator
2. get triggered on "git -tag v..." and update a version.go file
3. clean up the git log

I never got around to making something decent. Especially since I started feeling uncertain how I wanted the changelog generator to behave. Either it can generate everything from commit names or use issues with proper label use to figure out changes/fixes. This could also allow it to detect a breaking/minor/patch changes, which would be great to automate - but ofc an option for manual change is required. I'm getting a bit obsessed with automating my workflows.

**Comment by leogr** [comment]
> I think the only thing relevant for a library project would be the changelog generation and creating the release, right?

Correct!

> We could maybe add another binary that does only the changelog and release parts Or maybe a `--release-only` flag... or maybe on builds set a flag `library: true` and ignore it...

I was thinking the same thing. Basically, we should just skip the `main` function check.

> The fact is: I don't know how a good api for that would look, neither the side effects
> 
> We can try to hack something together though... I'll open to it if we find a good way of doing it...

I will try to experiment a bit and make a PR, eventually - hope tomorrow. Anyway, I totally agree that we have to find a good way, not just a hack :)

**Comment by leogr** [comment]
Hey @caarlos0 I did it https://github.com/goreleaser/goreleaser/pull/1419

Let me know what do you think about it!

Thanks in advance :)

**Comment by caarlos0** [comment]
Thanks @leogr, in my head I was thinking it would require way more changes 🙏

Will release this soon :)
